/** Basic user routes */
export const ROOT_PERMISSION = 'ROOT'
export const HOME_PERMISSION = 'HOME'

// Dashboard routes
export const DASHBOARD_PERMISSION = 'DASHBOARD'

// Information routes
export const FAQ_PERMISSION = 'FAQ'
export const HELP_PERMISSION = 'HELP'

// Profile routes
export const PROFILE_PERMISSION = 'PROFILE'
export const PROFILE_ACTIVITY_PERMISSION = 'PROFILE_ACTIVITY'
export const PROFILE_INFORMATION_PERMISSION = 'PROFILE_INFORMATION'
export const PROFILE_EMPLOYMENT_PERMISSION = 'PROFILE_EMPLOYMENT'
export const PROFILE_PASSWORD_PERMISSION = 'PROFILE_PASSWORD'

// User routes
export const USER_MANAGEMENT_PERMISSION = 'USER_MANAGEMENT'

// Country routes
export const COUNTRY_MANAGEMENT_PERMISSION = 'COUNTRY_MANAGEMENT'

// Organization  routes
export const ORGANIZATION_MANAGEMENT_PERMISSION = 'ORGANIZATION_MANAGEMENT'

// Organization  routes
export const QUESTION_MANAGEMENT_PERMISSION = 'QUESTION_MANAGEMENT'

// Report routes
export const REPORT_PERMISSION = 'REPORT'
